const BaseEvents = {
    BASE_EVENT_WEBRTC_NOT_SUPPORT : 'BASE_EVENT_WEBRTC_NOT_SUPPORT',
    BASE_EVENT_WEBRTC_ICE_CANDIDATE_ERROR : 'BASE_EVENT_WEBRTC_ICE_CANDIDATE_ERROR'
};
export default BaseEvents;