const Events = {
	WEBRTC_NOT_SUPPORT : 'WEBRTC_NOT_SUPPORT',
	WEBRTC_ICE_CANDIDATE_ERROR : 'WEBRTC_ICE_CANDIDATE_ERROR',
	WEBRTC_OFFER_ANWSER_EXCHANGE_FAILED:'WEBRTC_OFFER_ANWSER_EXCHANGE_FAILED',
	WEBRTC_ON_REMOTE_STREAMS:'WEBRTC_ON_REMOTE_STREAMS',
	WEBRTC_ON_LOCAL_STREAM:'WEBRTC_ON_LOCAL_STREAM'
};

export default Events;